### ISSUE TITLE
Write launch post for social media sharing

### ISSUE THREAD

**Issue by punnypenguins** [punnypenguins/projectdelve#2]
- [ ]  Jot down points i need to hit
- [ ]  Decide which sites to publish it on
- [ ]  Draft post
- [ ]  Make sure links work
- [ ]  Publish on chosen sites
